### ISSUE TITLE
Question: Frontend Project!

### ISSUE THREAD

**Issue by BlueFalcon234** [nectarboy/gameboy#4]
Hey @nectarboy !

I came across this project and it looks really cool, emulation works perfect and integration aspect seems really cool. I know nothing about html, css, or JavaScript lol, and to learn, I want create a simple front end (a cross platform front end that could also work on mobile :) ).  I know that this project is under the MIT license which is pretty permissive, but I still wanted to ask if it's cool with you if I can use pollenboy as a backend core?

Thanks!

**Comment by mushrombrother** [comment]
Hi, thanks !
Course you can :D as long as credit goes where its due no problem
I always appreciate my projects being useful to others so feel free
